kind: pipeline
type: docker
name: Deploy to AWS

steps:
- name: Build UI
  image: node:14.0
  environment:
    API_URL: http://floatql.com/api/graphql/
    APP_ENV: production
  commands:
    - cd ui/
    - npm ci
    - 'npm run build:production'
- name: Deploy UI to S3
  image: plugins/s3
  settings:
    bucket: floatql
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    commands:
      - cd ui/
      - npm ci
      - npm run test
    source: ui/dist/*
    target: /
  depends_on:
    - Build UI

depends_on:
  - Build Images
