kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: floatcms/api
    dockerfile: ./api/Dockerfile
    context: ./api
    build_args_from_env:
      - env_file:
        - ./api/env/dev.properties
        - ./env.properties
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
