---
kind: pipeline
name: api-build

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: floatcms/api
    dockerfile: ./api/Dockerfile
    context: ./api
    build_args_from_env:
      - env_file:
        - ./api/env/test.properties
        - ./env.properties
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

services:
- name: db
  image: postgres:12-alpine
  environment:
    POSTGRES_USER: drone
    POSTGRES_PASSWORD: drone_pwd
    POSTGRES_MULTIPLE_DATABASES: float

---
kind: pipeline
name: ui-build

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: floatcms/ui
    dockerfile: ./ui/Dockerfile
    context: ./ui
    build_args_from_env:
      - env_file:
        - ./ui/env/test.properties
        - ./env.properties
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
