version: '3.7'

services:
  ui:
    image: floatcms/ui:latest
    expose:
      - 3000
    volumes:
      - ui_volume:/app/dist
    env_file:
      - ./ui/env/dev.properties
      - ./env.properties
  api:
    image: floatcms/api:latest
    volumes:
      - static_volume:/app/static
    expose:
      - 5000
    env_file:
      - ./api/env/production.properties
      - ./env.properties
      - ./aws.properties
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - static_volume:/home/app/web/ui
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  static_volume:
  ui_volume:
