version: '3.7'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser_pwd
      - POSTGRES_MULTIPLE_DATABASES=float

  api:
    tty: true
    stdin_open: true
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/src:/app
      - ./db/wait-for-postgres.sh:/wait-for-postgres.sh
    entrypoint: /wait-for-postgres.sh
    command: ["./manage.py", "runserver_plus", "0.0.0.0:8000"]
    depends_on:
      - db
    restart: on-failure
    environment:
      - DJANGO_SECRET_KEY=(｡◕‿‿◕｡)
      - DJANGO_DB_NAME=float
      - DJANGO_DB_HOST=db
      - DJANGO_DB_USER=testuser
      - DJANGO_DB_PASSWORD=testuser_pwd

      - APP_ENV=development
      - DJANGO_SETTINGS_MODULE=settings.settings
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost
    ports:
      - "8000:8000"

  ui:
    tty: true
    stdin_open: true
    build:
      context: ./ui
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    command: sh -c "npm install && npm run dev"
