version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.12.0
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-west-2
    volumes:
      - ./.localstack:/tmp/localstack
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser_pwd
      - POSTGRES_MULTIPLE_DATABASES=float
    ports:
      - "5432:5432"

  api:
    tty: true
    stdin_open: true
    build:
      context: ./api
      target: dev
      args:
        PIP_REQ: dev
    volumes:
      - ./api/src:/app
      - ./db/wait-for-postgres.sh:/wait-for-postgres.sh
    entrypoint: /wait-for-postgres.sh
    command: ["./manage.py", "runserver_plus", "0.0.0.0:8000"]
    depends_on:
      - db
    restart: on-failure
    env_file:
      - ./api/env/dev.properties
      - ./env.properties
      - ./aws.properties
    ports:
      - "8000:8000"
