version: '3.7'

services:
  api:
    image: floatcms/api:latest
    volumes:
      - static_volume:/app/static
    expose:
      - 5000
    env_file:
      - ./production.properties
      - ./env.properties
      - ./aws.properties
  nginx:
    image: floatcms/nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  static_volume:
