version: '3.7'

services:
  api:
    image: floatcms/api:latest
    volumes:
      - static_volume:/app/static
    expose:
      - 5000
    env_file:
      - ./production.properties
      - ./env.properties
      - ./aws.properties
  nginx:
    image: floatcms/nginx
    volumes:
      - static_volume:/home/app/web/static
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
