version: '3.7'

services:
  api:
    image: floatcms/api:latest
    volumes:
      - static_volume:/app/static
    expose:
      - 5000
    env_file:
      - ./production.properties
      - ./env.properties
      - ./aws.properties
  nginx:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/static
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: kevin.a.cunanan@gmail.com
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - api

volumes:
  static_volume:
  letsencrypt:
