# Generated by Django 2.1.8 on 2019-05-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_key', to='sites.Site')),
            ],
        ),
    ]
