# Generated by Django 2.1.7 on 2019-02-18 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('slug', 'owner')},
        ),
    ]
