# Generated by Django 3.0.9 on 2020-08-13 01:14

import apps.float.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=apps.float.storage_backends.MediaStorage(), upload_to='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='sites.Site')),
            ],
        ),
    ]
