# Generated by Django 2.1.5 on 2019-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_assign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_be_assigned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_read_only',
        ),
    ]
