# Generated by Django 2.1.5 on 2019-01-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190125_1139'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
