# Generated by Django 2.2.3 on 2020-01-06 02:00

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True), blank=True, size=None)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='sites.Site')),
            ],
            options={
                'unique_together': {('slug', 'site')},
            },
        ),
        migrations.CreateModel(
            name='FlockColumnHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('field', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('long_text', 'Long Text'), ('html', 'html'), ('url', 'URL'), ('image', 'Image')], default='text', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('slug', models.SlugField(max_length=15)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='flocks.Flock')),
            ],
            options={
                'unique_together': {('flock', 'slug')},
            },
        ),
    ]
