# Generated by Django 3.0.9 on 2020-08-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='sites.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='flockcolumnheader',
            unique_together={('flock', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='flock',
            unique_together={('slug', 'site')},
        ),
    ]
