# Generated by Django 3.0.9 on 2020-08-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_auto_20200820_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flockcolumnheader',
            name='field',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('MARKDOWN', 'Markdown'), ('OBJECT', 'Object'), ('ARRAY', 'Array')], default='TEXT', max_length=25),
        ),
        migrations.AlterField(
            model_name='flockcolumnheader',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='flocks.Flock'),
        ),
        migrations.AlterUniqueTogether(
            name='flockcolumnheader',
            unique_together={('parent', 'slug'), ('flock', 'slug')},
        ),
    ]
