# Generated by Django 3.0.9 on 2020-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_auto_20200118_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flockcolumnheader',
            name='field',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('MARKDOWN', 'Markdown')], default='TEXT', max_length=25),
        ),
        migrations.AlterField(
            model_name='flockcolumnheader',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flockcolumnheader',
            name='slug',
            field=models.SlugField(max_length=25),
        ),
    ]
