# Generated by Django 3.0.9 on 2020-08-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0003_auto_20200812_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='flockcolumnheader',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='flocks.FlockColumnHeader'),
        ),
        migrations.AlterField(
            model_name='flockcolumnheader',
            name='field',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('MARKDOWN', 'Markdown'), ('OBJECT', 'Object')], default='TEXT', max_length=25),
        ),
    ]
