# Generated by Django 2.1.7 on 2019-02-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('long_text', 'Long Text'), ('html', 'html'), ('url', 'URL'), ('image', 'Image')], default='text', max_length=50)),
                ('order', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=15)),
            ],
        ),
    ]
