# Generated by Django 2.1.8 on 2019-05-28 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_page_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pagecolumnheader',
            unique_together={('page', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug', 'site')},
        ),
    ]
