# Generated by Django 3.0.9 on 2020-08-20 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_page_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pagecolumnheader',
            unique_together={('page', 'slug'), ('parent', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug', 'site')},
        ),
    ]
